import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { validateApiKey, unauthorizedResponse } from "@/lib/api-auth";

/**
 * @swagger
 * /api/v1/generated-images:
 *   get:
 *     tags:
 *       - Generated Images
 *     summary: Retrieve images generated by a user
 *     description: Returns a list of images generated by the specified user (from external apps).
 *     security:
 *       - ApiKeyAuth: []
 *     parameters:
 *       - in: query
 *         name: userId
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the user to fetch images for
 *     responses:
 *       200:
 *         description: List of generated images
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       id:
 *                         type: integer
 *                       userId:
 *                         type: integer
 *                       imageUrl:
 *                         type: string
 *                       prompt:
 *                         type: string
 *                       type:
 *                         type: string
 *                       createdAt:
 *                         type: string
 *                         format: date-time
 *       400:
 *         description: Missing userId parameter
 *       401:
 *         description: Unauthorized
 */
export async function GET(req: NextRequest) {
	if (!validateApiKey(req)) return unauthorizedResponse();

	const { searchParams } = new URL(req.url);
	const userId = searchParams.get("userId");

	if (!userId) {
		return NextResponse.json(
			{ success: false, message: "Missing userId parameter" },
			{ status: 400 }
		);
	}

	try {
		// Fetch data from Prisma 'ImageGeneration' table
		const images = await prisma.imageGeneration.findMany({
			where: {
				userId: Number(userId),
			},
			orderBy: {
				createdAt: "desc",
			},
		});

		return NextResponse.json(
			{
				success: true,
				data: images,
			},
			{ status: 200 }
		);
	} catch (error: any) {
		return NextResponse.json(
			{ success: false, message: error.message },
			{ status: 500 }
		);
	}
}
